addSbtPlugin("com.eed3si9n"       % "sbt-assembly" % "2.3.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.4.7")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix" % "0.14.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt" % "2.5.4")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"    % "1.5.11")
