addSbtPlugin("com.eed3si9n"       % "sbt-assembly"    % "2.3.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.4.7")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"    % "0.14.3")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.5.4")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"       % "2.0.13")
addSbtPlugin("org.wartremover"    % "sbt-wartremover" % "3.4.1")
